tiagosiebler/binance

- .eslintrc.js
- CHANGELOG.md
- README.md
- lib/rest.js
- package.json
Adding some functionality to try and handle time drift within the library, rather than people attempting to adjust their clocks.
> Add in library time synchronization

- lib/rest.js
I thought it might help to simplify this portion of the code by joining the two paths.
> Combine the separated promise/callback paths in _makeRequest.

- CHANGELOG.md
- lib/processor.js
- package.json
- test/processor-tests.js
- yarn.lock
- Bump package version to 1.3.4
- Update change-log (used merged PR history with #references, hope I caught everything)
- Updated contributors 🙃 
Should be ready for npm publish once this is merged.
> Bump version, changelog & contributors

- lib/rest.js
sapi/v1/capital/deposit/hisrec
sapi/v1/capital/config/getall
> depositAddressWithNetwork And allCoinsInformation

- CHANGELOG.md
- lib/rest.js
- lib/ws.js
- package.json
-   Bump dependencies. #104, #106, #107, #108.
-   Add depositAddressWithNetwork and allCoinsInformation REST methods. #100
> V1.3.6: dependencies & two new REST methods

- src/spot-client.ts
- test/spot/private.test.ts
> Changed getAccountInformation() from postPrivate to getPrivate and also addes test for the same.

- examples/ws-close.ts
- package.json
- src/websocket-client.ts
Hello,
I've fixed the problem with the `willReconnect` parameter.
Tell me if I overlooked something :)
fixes #154
> Fixes will not reconnect case in websocket

- README.md
- package.json
- src/types/spot.ts
- src/util/ws-utils.ts
- src/websocket-client.ts
- fix(#165): add missing properties from spot type
- fix(#164): change handling for user data respawn failure
- clear ping/pong timer on any incoming message. 
- add option to disable heartbeat for ws (not recommended by default).
- fix(#168): safety on terminate ws call
> v2.0.18: add missing spot type properties. change user data respawn failure handling. improve ws heartbeat handling. safety for ws close in browsers.

- src/main-client.ts
- src/types/shared.ts
- src/types/spot.ts
Hello!
Due to the nature of Binance margin heavily overlapping with existing spot types; I have created this basic PR to verify if my approach is desired/correct.
Welcoming any comments/suggestions/changes.
Happy to add the rest of the margin types and functions once confirmed.
> Adding basic support for margin endpoints

- package-lock.json
- package.json
- src/util/BaseRestClient.ts
- src/util/requestUtils.ts
- test/response.util.ts
- test/spot/private.test.ts
To test this, `npm install binance@beta`
> Fix(#179): tidy signature process & fix parameter encoding for some signed POST requests

- package.json
- src/types/websockets.ts
- src/websocket-client.ts
Seems ws data isn't consistent for the margin type param. Corrected definitions for the ws event.
> fix types for account update

- src/types/spot.ts
> Fixed typo in `interface SpotOrder`

- package.json
> v2.0.24: fix typo in SpotOrder interface

- examples/ws-public.ts
- examples/ws-userdata.ts
- package.json
- src/index.ts
- src/util/WsStore.ts
- src/util/typeGuards.ts
- src/websocket-client.ts
Closes #191 
- Adds type guards for easier implementation of ws event handlers (type guards are incomplete - PRs welcome!)
- Improve checks and handlers for duplicate calls to subscribe to user data event streams
> add type guards for ws events (#190), add checks for duplicate user data streams & timers (fixes #191)

- package.json
> v2.0.26: updating generateNewOrderId() to support nanoid #181

- src/main-client.ts
- src/types/spot.ts
- test/spot/private.test.ts
Closes #  NA
This PR adds all endpoints to interact with Binance Sub Accounts (excluding 4 referenced in `main-client.ts`). I completed this addition without the intention of publishing, but figured if it is in line with your continuous development, it may be of value.
If its not something you'd like to add at this time - let me know and I'll close the PR. :)
This change adds a significant amount of new interfaces/types into `types/spot.ts`. I have tried to share and consolidate where possible, but it is still a large addition.
I performed some local testing, but have not written any test cases at this time.
> Adding Sub Account Endpoints

- package.json
> feat(#210): v2.0.30 - extended typeguards for raw websocket events

- .circleci/config.yml
- .github/workflows/npmpublish.yml
- README.md
- package.json
- tsconfig.json
> readme updates

- package.json
- src/types/shared.ts
> v2.0.33, feat(#215): add GTE_GTC TIF option

- package.json
- src/util/typeGuards.ts
> v2.0.34, fix(#217): typeguard for individual vs array mark price update events

- package.json
- src/util/typeGuards.ts
> v2.0.35: add 24hr ticker array type guard for futures ws

- src/types/futures.ts
Add missing types for FuturesAccountInformation
> Add missing types for FuturesAccountInformation

- src/main-client.ts
- src/types/shared.ts
- src/types/spot.ts
- test/spot/staking.test.ts
> Add Staking endpoints

- package.json
Release v2.0.38
- Add missing types for FuturesAccountInformation #232
- Add endpoint for isolated margin account info #233 
- Add staking endpoints #234
> v2.0.38: #232 missing futures acc types, #233 endpoint for isolated margin account info, #234 staking endpoints

- src/types/futures.ts
- src/usdm-client.ts
Mark price return type
https://binance-docs.github.io/apidocs/futures/en/#mark-price
> Add return type to getMarkPrice

- package.json
> v2.0.39: add missing return type (#236)

- package.json
- src/main-client.ts
- src/types/spot.ts
Add basic bswap ops:
- getBSwapLiquidity
- addBSwapLiquidity
- removeBSwapLiquidit
- getBSwapOperations(
> Add some bswap endpoints

- README.md
- package.json
- src/coinm-client.ts
- src/index.ts
- src/types/coin.ts
- src/util/requestUtils.ts
- test/futures-coinm/private.test.ts
Little bit bigger PR this time. 
Adding the CoinM Client and some endopoints. 
Tried to keep the same structure as the other clients. 
Updated the version to 2.1.0 as its adds a new, non-breaking feature.
> v2.1.0 add CoinM futures client

- package.json
- src/types/futures.ts
Missing 
- notional
- isolatedWallet
https://binance-docs.github.io/apidocs/futures/en/#position-information-v2-user_data
> add missing return type

- package.json
- src/main-client.ts
- src/types/spot.ts
some Broker & Savings endpoints were added
ISSUE: #243
> feat: add first Broker & Savings endpoints

- examples/ws-userdata.ts
- src/coinm-client.ts
- src/types/shared.ts
- src/util/requestUtils.ts
- src/websocket-client.ts
> coinm ws partly implemented

- package.json
> v2.1.3(#247): expanded coinm support

- README.md
- package.json
- src/types/websockets.ts
> v2.2.1: fix ws event interface property typo. Update readme. Fix(#263): typo in jsdoc.

- examples/ws-public-spot-trades.ts
- package.json
- src/util/typeGuards.ts
> v2.2.3: add spot trade ws example & type guard

- package-lock.json
- package.json
> v2.2.5: feat(#274): add more broker endpoints

- examples/ws-userdata.ts
- src/types/websockets.ts
- src/util/typeGuards.ts
Hi, I'd like to submit this pull request.
Contains two commits, more info provided in commit details
Cheers
> Add 10 new typeguards and a small fix in WsFormattedMessage type hierarchy

- package.json
> v2.2.7: feat(#277) add more user data type guards

- .circleci/config.yml
> Use self-hosted CircleCI runner

- package.json
- src/util/typeGuards.ts
> v2.2.8: feat() run linter & add type guard for ws force order events

- package.json
> v2.3.0: feat(#293, #284): add support for RSA auth

- README.md
- package-lock.json
- package.json
> v2.3.1: readme updates & bump dependency

- .circleci/config.yml
- package.json
- src/types/websockets.ts
> v2.3.2: fix time in force param name for futures user data formatted evt

- src/types/websockets.ts
> add two missing properties in futures order update event

- examples/ws-userdata-connection-safety.ts
- package-lock.json
- package.json
- src/websocket-client.ts
- feat(#302) release undocumented raw trades websockets.
- slightly expand ws user data samples.
> v2.3.4: feat(#302) release undocumented raw trades websockets. 

- src/coinm-client.ts
just copied usdm and modified at a bit, it should have same interface as usdm the difference is only fapi -> dapi
https://github.com/tiagosiebler/binance/issues/152
not sure about v2 endpoints for balances if they work, I didn't check all methods, just basic
> Copy usdm and modify it to be coinm

- README.md
- package-lock.json
- package.json
> v2.4.1: fix typo in readme

- examples/rest-private-rsa.md
- examples/rest-private-rsa.ts
- package.json
- src/util/browser-support.ts
- src/util/node-support.ts
- Improve detection for RSA auth. 
- Add example for RSA auth, including docs.
> v2.5.1: fix(#284) improve detection for rsa auth. Add example for RSA auth

- package.json
- src/types/spot.ts
- Updated EnumUniversalTransferType types
- Added params to UniversalTransferParams
Source: https://binance-docs.github.io/apidocs/spot/en/#user-universal-transfer-user_data
> v2.5.2: fix(#316) add params and universal transfer types

- .prettierrc
- examples/ws-close.ts
- examples/ws-proxy-socks.ts
- examples/ws-public.ts
- package.json
> v2.5.3: feat(#319) add socks proxy support to ws client

- examples/tracking-candles.ts
> chore(): minor sample fixes

- package-lock.json
- package.json
- src/types/websockets.ts
> v2.7.0: fix(): update futures ws order types to reflect reality better

- package-lock.json
- package.json
> v2.8.1, fix(#337) marginType response type for position info endpoint

- package-lock.json
- package.json
> v.2.8.2: feat(#339) use globalThis for browser sign

- package-lock.json
- package.json
- src/util/requestUtils.ts
- feat(#341) improve symbol exchange info typings
- chore(): linting and cleaning in request utils
> v.2.8.3: feat(#341) improve symbol exchange info typings, chore(): linting and cleaning in request utils

- package-lock.json
- package.json
- src/types/shared.ts
> v2.8.4: fix(): oco client order ID type

- README.md
- package-lock.json
- package.json
- src/coinm-client.ts
- src/usdm-client.ts
v2.8.5: fix(#336) fix handling for cancel batch orders endpoint. chore() readme updates. chore() linting in coinm client.
> v2.8.5: fix(#336) fix handling for cancel batch orders endpoint. chore() readme updates. chore() linting in coinm client.

- package-lock.json
- package.json
- src/types/shared.ts
- src/types/spot.ts
Added `trailingDelta` to `NewSpotOrderParams` and changed the casing in `shared.ts` for consistency.
> Add trailingDelta to NewSpotOrderParams

- examples/rest-usdm-private-get.ts
- package-lock.json
- package.json
- src/main-client.ts
- src/types/spot.ts
> v2.8.7: feat(#351) add convert endpoints

- package-lock.json
- package.json
> v2.8.8: fix(#353) swap request interfaces

- package-lock.json
- package.json
> v2.8.10: feat(#362) fix usdm get trades return type typo

- package-lock.json
- package.json
- src/websocket-client.ts
feat(#366): slightly improve reconnect param naming. bump dependencies
> feat(): slightly improve reconnect param naming. bump dependencies

- src/coinm-client.ts
- src/main-client.ts
- src/util/BaseRestClient.ts
- src/util/requestUtils.ts
default value is off.
function style is
https://t.me/nodetraders/27723
> add filterUndefinedParams to rest-client

- src/coinm-client.ts
- src/usdm-client.ts
> NewOrder type fixing

- .circleci/config.yml
- examples/rest-spot-public.ts
- package.json
- src/main-client.ts
- src/types/shared.ts
> Add support for multi-symbol ticker param, with better return type signatures

- package.json
- src/types/websockets.ts
> Add force Orders type definition

- examples/ws-public-spot-orderbook.ts
- package-lock.json
- package.json
- src/types/websockets.ts
- src/util/typeGuards.ts
- src/websocket-client.ts
> v2.9.1: add typeguard for formatted orderbook events, with example

- package.json
- src/main-client.ts
- src/types/spot.ts
- src/usdm-client.ts
-Add change order in usdm-m
-Add cancel-and-replace on spot.
> v2.9.2: feat() add order amend/replace

- package-lock.json
- package.json
> v2.9.3: feat(#387) add order amend/replace

- package.json
- src/main-client.ts
Replaced some deprecated endpoints for updated flexible savings ones. (old endpoints returned "This endpoint has been deprecated, please remove as soon as possible."
changed end points
Replaced some deprecated endpoints for updated flexible savings ones. (old endpoints returned "This endpoint has been deprecated, please remove as soon as possible."
> v2.9.4: update flexible savings endpoints

- .github/workflows/npmpublish.yml
- .github/workflows/test.yml
- package.json
- src/types/websockets.ts
- test/futures-coinm/private.test.ts
- test/futures-usdm/private.test.ts
- test/futures-usdm/public.test.ts
- test/proxy.util.ts
- test/spot/private.test.ts
- test/spot/public.test.ts
- test/spot/staking.test.ts
> v2.9.5: feat() use github action for test, feat() publish with provenance, fix(#398) bestBid/bestAskPrice property in 24hr ticker formatted type

- .github/workflows/npmpublish.yml
- README.md
- package.json
> v2.9.6: chore() readme update & remove redundant publish step

- test/futures-usdm/private.test.ts
Quick fix to prevent the build from failing before #422 goes in
> fix(): broken test

- package-lock.json
- package.json
- src/main-client.ts
- src/types/spot.ts
- test/futures-usdm/private.test.ts
> v2.12.0: fix type name consistency, bump dependency

- test/futures-usdm/private.test.ts
> chore(): update test after sub acc credits upgrade

- examples/rest-spot-private-autoinvest.ts
> fix(): auto invest api calls

- examples/ws-public.ts
- package-lock.json
- package.json
- src/websocket-client.ts
- test/futures-usdm/private.test.ts
> v2.12.3: feat() add contract info stream

- docs/endpointFunctionList.md
- package-lock.json
- package.json
- src/main-client.ts
- src/types/futures.ts
- src/types/websockets.ts
- src/usdm-client.ts
> v2.13.3: feat(): Added new convert  and PMPro endpoints

- package-lock.json
- package.json
> v2.13.4: chore() bump audit dependencies

- package-lock.json
- package.json
- src/main-client.ts
- src/types/spot.ts
Updated new changes for Binance API as of today. 
Build fails bcs of location, locally build worked okay.
> feat(): updated Margin endpoints

- .github/workflows/test.yml
Trigger actions on PR and Dispatch too
> chore(): expand action triggers for e2e tests

- package-lock.json
- package.json
- src/types/websockets.ts
- src/util/beautifier-maps.ts
- test/beautifier.test.ts
> feat(): updated websocket topics

- package.json
- src/types/spot.ts
Added some missing fields into CoinNetwork interface
> Types updated for All Coins' Information response

- package-lock.json
- package.json
- src/main-client.ts
- src/types/spot.ts
Adding correct request params to Redeem flexible product in SimpleEarn
> correct params on simple earn redeem flexible products

- package-lock.json
- package.json
- src/types/futures.ts
- src/types/shared.ts
> feat(v.2.15.8): updated futures fundingRateHistory response type, updated spot NewOrderList request

- docs/endpointFunctionList.md
- examples/apidoc/MainClient/getOnboardedVASPList.js
- examples/apidoc/MainClient/getTravelRuleDepositHistory.js
- examples/apidoc/MainClient/getTravelRuleWithdrawHistory.js
- examples/apidoc/MainClient/getTravelRuleWithdrawHistoryV2.js
- examples/apidoc/MainClient/submitTravelRuleDepositQuestionnaire.js
- examples/apidoc/MainClient/withdrawTravelRule.js
- package-lock.json
- package.json
- src/main-client.ts
- src/types/futures.ts
- src/types/spot.ts
- src/usdm-client.ts
feat(): added travel rule endpoints, updated futures response type, updated examples and endpoint map
fixes #517
fixes #518
> feat(v2.15.11): added travel rule endpoints, updated futures response type, updated examples and endpoint map

- test/futures-usdm/private.test.ts
Updated SubmitMultipleOrders() test to include the new error code we get.
> chore(): updated test response

- package-lock.json
- package.json
- src/types/futures.ts
> feat(v2.15.12): updated newOrderRespType for futures client

- package-lock.json
- package.json
- src/usdm-client.ts
chore(): updated type for futures cancelAllOpenOrders()
Fixes #524
> chore(): updated type for futures cancelAllOpenOrders()

- src/types/websockets/ws-api-requests.ts
- src/types/websockets/ws-api-responses.ts
- src/types/websockets/ws-api.ts
feat(): added wsapi spot and futures endpoints, with corresponding req/resp types
> feat(): added wsapi spot and futures endpoints, with corresponding req/resp types

- docs/endpointFunctionList.md
- examples/apidoc/MainClient/get24hrChangeStatistics.js
- examples/apidoc/MainClient/getSubAccountFuturesPositionMoveHistory.js
- examples/apidoc/MainClient/subAccountMovePosition.js
- examples/apidoc/USDMClient/get24hrChangeStatististics.js
- package-lock.json
- package.json
- src/main-client.ts
- src/types/spot.ts
feat(2.15.16): Updated types, added new subaccount functions
> feat(2.15.16): Updated types, added new subaccount functions

- package-lock.json
- package.json
- src/types/portfolio-margin.ts
fix(v2.15.17): removed recvwindow from portfolio margin types
> fix(v2.15.17): removed recvwindow from portfolio margin types

- docs/endpointFunctionList.md
- examples/apidoc/MainClient/amendOrderKeepPriority.js
- examples/apidoc/USDMClient/getInsuranceFundBalance.js
- package-lock.json
- package.json
- src/main-client.ts
- src/types/futures.ts
- src/types/shared.ts
- src/types/spot.ts
- src/usdm-client.ts
feat(v2.15.19): added amendKeepPriority, getInsuranceFuncBalance, updated types
> feat(v2.15.19): added amendKeepPriority, getInsuranceFuncBalance, updated types

- examples/WebSockets/ws-public.ts
- src/util/typeGuards.ts
chore(): checked all ws public topics for type guards
> chore(): checked all ws public topics for type guards

- package-lock.json
- package.json
- src/types/shared.ts
- src/types/spot.ts
> feat(v2.15.20): updated margin endpoints types

- src/types/websockets/ws-events-raw.ts
**Reference**:
- https://github.com/tiagosiebler/binance/blob/wsapi/src/types/websockets/ws-events-formatted.ts#L416
- https://developers.binance.com/docs/derivatives/usds-margined-futures/websocket-market-streams/Mark-Price-Stream#response-example
As part of the PR, make sure you have:
> add WsMessageMarkPriceUpdateEventRaw

- src/websocket-api-client.ts
As part of the PR, make sure you have:
> Update optional wsapi futures

- docs/endpointFunctionList.md
As part of the PR, make sure you have:
> chore(): added endpoint map

- README.md
- llms.txt
- package-lock.json
- package.json
- src/types/websockets/ws-general.ts
- src/util/requestUtils.ts
- src/util/websockets/websocket-util.ts
As part of the PR, make sure you have:
> feat(): added mm urls
