tiagosiebler/binance

lib/ws.js
First of all thanks for creating this wrapper, it's really helpful. 👍 
I was trying to use this wrapper to connect to the Finance web socket and got this error:
```
/Users/aslam/Documents/projects/gdax/node_modules/binance/lib/ws.js:20
eventHandler(this._beautifier.beautifier(data, data.e + 'Event'));
^
TypeError: this._beautifier.beautifier is not a function
at WebSocket.ws.on (/Users/aslam/Documents/projects/gdax/node_modules/binance/lib/ws.js:20:43)
at emitOne (events.js:115:13)
at WebSocket.emit (events.js:210:7)
at Receiver._receiver.onmessage (/Users/aslam/Documents/projects/gdax/node_modules/ws/lib/WebSocket.js:143:47)
at Receiver.dataMessage (/Users/aslam/Documents/projects/gdax/node_modules/ws/lib/Receiver.js:389:14)
at Receiver.getData …
```
=> fix typo in ws.js

lib/rest.js
某些时候body可能如下，这样JSON.parse会报错。
```
<html>
<head>
<title>500 Internal Server Error</title>
</head>
<body bgcolor="white">
<center>
<h1>500 Internal Server Error</h1>
</center>
</body>
</html>
```
=> 修复接口调用错误时,JSON.parse抛出异常

lib/rest.js
When an HTTP 4XX or 5XX error is returned, the payload will be a PNG image returned by Binance, instead of passing this back as the error we send an error object with the response code. This allows error handling to be implemented, including the ability to respond to rate limits.
=> Produce a real Error object on HTTP errors

.gitignore, index.d.ts, package.json
This is a basic start for supporting TypeScript developers. The `index.d.ts` file defines `BinanceRest` and its public API.
If people fine this useful they should open more PRs that define the response objects for each public function.
See #14 for the original issue.
=> Add top level type definitions for TypeScript users

README.md, lib/rest.js
Solves https://github.com/zoeyg/binance/issues/58; one can now configure a proxy by doing:
```
new BinanceRest({
...,
requestOptions: {
proxy: 'http://myproxy:3128'
}
});
```
=> Add requestOptions (proxy support + more)

README.md, lib/binance.js, lib/processor.js, test/processor-tests.js
@apexearth did a great job making a processFilters utility function to adhere with Binance's number formatting & lot size rules. Unfortunately the original PR (#43) carries unrelated changes and seems to have gone stale.
This PR has these processFilters stripped out from #43 - without the unrelated websocket changes.
=> Strip out processFilter workflows from #43

lib/rest.js, lib/ws.js, package.json, test/tests.js
This PR addresses two scenarios.
1. A userData websocket connection is opened and closed deliberately. The current design causes the module to keep sending keep alive requests indefinitely. See #70 
2. A network issue caused the websocket to drop, which is easily handled by opening a new connection. The old listen key expires, yet the old logic keeps sending keep alive requests indefinitely. Over time this can quickly multiply at many overlapping keep alive requests putting pressure on the rate limits with binance's APIs.
Key changes:
- The keepAlive timer interval is stored.
- A new call to onUserData clears an old interval if one is found.
- If a keep alive request sees an error code indicating the listen key is no longer valid, the keep alive timer is cleared (as the websocket already …
=> Clear onUserData keep alive interval if new user data socket opens or previous one is invalid. Fixes #70.

lib/beautifier.js
**Summary**
- `newItem` is initialized as an array and then the push method is called on it. This is a typo and it should read `newArray.push`.  
- I changed `newItem.push` to `newArray.push` @ line 215 in `lib/beautifier.js` to fix `TypeError: newItem.push is not a function`.
=> FIXED typo in lib/beautifier.js

README.md, lib/beautifier.js
Supports the handling of event type ```outboundAccountPosition```  for the user data stream (onUserData).
This event is similar to the ```outboundAccountInfo``` event type but is more compact and only gives the affected balances. 
```javascript
{
"e": "outboundAccountPosition", 
"E": 1564034571105,                 
"u": 1564034571073,            
"B": [                                        
{
"a": "ETH",                         
"f": "10000.000000",            
"l": "0.000000"  
}
]
}
```
This event type was introduced in 2019-09-15 and described at https://binance-docs.github.io/apidocs/spot/en/#change-log:
> New Event Type ```outboundAccountPosition```; ```outboundAccountPosition``` is sent any time an account's balance changes and contains the assets that could have changed by the …
=> Supports the handling of event type "outboundAccountPosition" in user data stream

CHANGELOG.md, package-lock.json, package.json, src/util/BaseRestClient.ts, src/util/node-support.ts
- Expose time sync offset getter/setter in base client. `getTimeOffset()/setTimeOffest(value)`.
- Add handler to signMessage method, falling back to browser equivalent if method is not a function (react/preact/#141).
=> Time sync offset util methods & createHmac fallback for react/preact

src/types/spot.ts
Adding missing optional parameter 'withdrawOrderId' to interface 'WithdrawHistoryParams' in spot.ts. See issue #145 for more information.
=> #145 - Adding missing param withdrawOrderId

package-lock.json, package.json, src/types/shared.ts, src/types/spot.ts, src/util/requestUtils.ts
This PR migrates the `generateNewOrderId()` function from utilising `Math.random()` to `nanoid()`. This change does include the addition of a new dependency, however, I believe this is a much cleaner and future-proofed approach.
The max length of a `newClientOrderId` is 36. This method uses a maximum of 35 characters.
Let me know if you have any feedback/suggestions!
** Low priority to merge.
=> updating generateNewOrderId() to support nanoid

src/types/websockets.ts
=> Add missing type to WsMessageBookTickerEventFormatted interface

.prettierrc, package-lock.json, package.json, src/main-client.ts, src/types/futures.ts, src/types/shared.ts, src/types/spot.ts, src/usdm-client.ts
Minor fixes & refinements:
- Fixes #200, where passing a symbol to getExchangeInfo was constructing an incorrect URL.
- Fixes #187, where submitNewOrder type param was not pointing to the futures type enum.
=> v2.0.29: type fixes for new order type in futures & getExchangeInfo with symbol param

src/types/websockets.ts, src/util/typeGuards.ts
This change adds the ability to create type guards for raw Futures websocket events. Also included is some common typeguards.
`package.json` version is _**not**_ yet bumped in this PR.
=> Adding type guards for raw websocket messages

package.json, src/types/futures.ts, src/usdm-client.ts, src/util/BaseRestClient.ts, test/futures-usdm/private.test.ts, test/spot/private.test.ts
- fixes #162 - submitMultipleOrders for futures client. Request body was wrong & numeric types here should be passed as strings (thanks to everyone that helped figure this out)
- misc linting
- add return type to futures get symbol price ticker method
=> v2.0.32: fix(#162): submitMultipleOrders support for futures client

examples/rest-future-bracket-order.ts, src/types/shared.ts
Added an extra option 'GTE_GTC' to the type 'OrderTimeInForce'.
This option is required to place an bracket order in futures
Bracket (OTOCO) order can be placed from binance website in futures.
We can do same thing using api but it is not in the binance api documentation.
But for that we need an un-documented 'GTE_GTC' option for time-in-force.
Also added an example of how place OTOCO order.
=> To enable/place BRACKET (OTOCO) ORDER, added GTE_GTC TIF option

package.json, src/main-client.ts, src/types/spot.ts
Add missing Isolated Margin Account Info that was on the "TODO list"
https://binance-docs.github.io/apidocs/spot/en/#query-isolated-margin-account-info-user_data
=> Add Isolated Margin Account Info

package-lock.json, package.json, src/main-client.ts
- Fixes #245 (endpoint was marked as private, binance didn't like receiving auth params in a public request)
=> fix(#245): omit auth for public endpoint

README.md, package.json, src/types/shared.ts
- Fixes #254 (some OCO params should be optional)
- Adds some newer missing OCO params to request type
- Update readme a bit.
=> v2.1.6: fix(#254): some OCO response types are optional. add missing OCO request properties.

README.md, package.json, src/main-client.ts, src/types/shared.ts, src/types/spot.ts, src/util/BaseRestClient.ts, src/util/WsStore.ts, src/util/beautifier.ts, src/websocket-client.ts, test/beautifier.test.ts
- Add 1s kline interval to type. Fixes #258.
- Add savings endpoints from #246 (thanks for the initial PR @Mateo-P)
- Migrate ws client updates from bybit connector:
- Set default handler for internal error event, in case user isn't listening to it. Prevents crashes from missing handler, fixes #248. https://github.com/tiagosiebler/bybit-api/commit/750db0232ca9034b98c8902322c82863449aba2b
- Improve resilience & stability in reconnect workflows, based on improvements in bybit connector:
- https://github.com/tiagosiebler/bybit-api/commit/d3b2c65c2260bdceabba3814059f2fd62c0cc000
- https://github.com/tiagosiebler/bybit-api/commit/7c6d02ea8b86ed898a074683b269384f8300d525
- Improve type safety around ws client internals (state enum, timer tracking, ws store types)
- Fix "cumulative/cummulative" …
=> v2.2.0: 1s interval, ws client resilience, new savings endpoints, disable time sync by default

src/websocket-client.ts
Maybe a leftover from a copy and paste of the signature. On `subscribeSpotTrades` the comment says that it subscribes to candles, while instead it should say trades.
=> Changed candles to trades in js docs

package-lock.json, package.json, src/main-client.ts, src/types/futures.ts, src/types/shared.ts, src/usdm-client.ts
PR adds (reuses from futures) `Kline` type to spot `getKlines` function.
=> Add return type to `getKlines`

src/main-client.ts, src/types/spot.ts
Signed-off-by: MartoMcfly <martinpelaez@hotmail.es>
PR contains a feature which allows to to get the transfer history for sub accounts by calling the broker transfer api sapi/v1/broker/transfer
PR dosent generate any major changes and dosent moddify the behavior of the repo :)
=> Gets sub account transaction history

package.json, src/util/ws-utils.ts, src/websocket-client.ts
- Fix inconsistent wsKey construction for futures user data streams.
- Fix connection teardown/respawn, when listen key keep alive fails repeatedly.
- Fix userdata teardown when close & closeAll() methods are used to close connections.
=> v2.2.11: fix(#290): fixes & improvements for websocket listenkey keep alive failure handling & teardown

src/util/browser-support.ts, src/util/node-support.ts
This PR will add support for RSA keys.
The web implementation is based on the [MDN KPCS8](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/importKey#pkcs_8_import).
I've verified the node and browser result with the following command: 'echo -n 'TESTSTRING' | openssl dgst -sha256 -sign ./private_key.pem  | openssl enc -base64 -A'
Closes #284
=> Add support for RSA Keys

src/types/websockets.ts
Hello, I think the properties for the SpotBalanceFormatted interface are wrong
It corresponds to the SpotBalanceRaw definition ( probably a copy / paste that hasn't been edited then ^^ )
I changed them with the properties I get when I print my object in the console
=> fix SpotBalanceFormatted definition

src/main-client.ts
fix #297 
Old behavior: 
`Not all sent parameters were read; read '0' parameter(s) but was sent '1'.`
New behavior:
No Error
=> fix(#297): exchangeInfo accepts symbols as param

README.md, package-lock.json, package.json, src/coinm-client.ts, src/main-client.ts, src/types/futures.ts, src/types/shared.ts, src/types/spot.ts, src/usdm-client.ts
- feat(#305, #242) complete CoinM futures support in REST client. Thanks to efforts from @eugeneglova in making this happen.
=> v2.4.0: feat(#305, #242) complete CoinM futures support in REST client

examples/rest-usdm-order.ts, examples/rest-usdm-private-get.ts, package.json, src/usdm-client.ts
- #310 pointed out the REST API always returns an array, even when providing a symbol. 
- This updates the return type to match reality.
=> v2.5.0: fix(#310) return type on notional brackets endpoint to match what actually happens

src/websocket-client.ts
WebsocketClient support proxy 
```ts
import { isWsFormatted24hrTicker, isWsFormattedKline } from "binance";
import EventEmitter from "events";
const { SocksProxyAgent } = require('socks-proxy-agent');
import { outLogger } from "ROOT/common/logger";
import { WebsocketClient } from "ROOT/lib/binance"; // build local for test
import { Period } from "./interface";
export class BinanceWebSocket {
/** @see https://github.com/tiagosiebler/binance/blob/master/src/websocket-client.ts */
wsClient: WebsocketClient
constructor() {
this.init()
}
init() {
const agent = new SocksProxyAgent(process.env.http_proxy);
const wsClient = new WebsocketClient({
beautify: false,
wsOptions: {
agent: agent
}
}, {
silly: (...params) => {
outLogger.info('ws silly', ...params);
},
debug: (...params) => { …
```
=> feat: WebsocketClient support agents

examples/util/README.md, package-lock.json, package.json, src/logger.ts, src/types/websockets.ts
- feat() add 3 missing ignoreable properties to futures order trade update. 
- feat() Add timestamps to built in logger.
=> v2.6.1: feat() add 3 missing ignoreable properties to futures order trade update. Add timestamps to built in logger.

src/types/websockets.ts, src/util/beautifier-maps.ts, test/beautifier.test.ts
fix(beautifier): rename "transactionId" to "transactionTime" in ACCOUNT_UPDATE beautified event
- The key "T" in raw user data events messages is the transaction timestamp, therefore  it should be beautified to "transactionTime" instead of "transactionId" to avoid confusion
=> fix(beautifier): rename "transactionId" to "transactionTime" in ACCOUNT_UPDATE beautified event

src/util/browser-support.ts
web workers fail with window is not defined error, we just use globalThis
fixes https://github.com/tiagosiebler/binance/issues/280
=> use globalThis instead of window for web worker support

src/types/spot.ts
Add missing typings for `SymbolExchangeInfo`
See [change log](https://binance-docs.github.io/apidocs/spot/en/#change-log):
> 2022-12-05
> 
> Changes to GET /api/v3/exchangeInfo
> New fields defaultSelfTradePreventionMode and allowedSelfTradePreventionModes
> 2022-06-15
>
> GET /api/v3/exchangeInfo returns new field cancelReplaceAllowed in symbols list.
> 2019-11-13
> 
> Rest API
> 
> api/v3/exchangeInfo has new fields:
> quoteOrderQtyMarketAllowed
> baseCommissionPrecision
> quoteCommissionPrecision
=> Improve typings of SymbolExchangeInfo

src/types/futures.ts
fix typos and add `marginAsset`
example trade:
```ts
{
symbol: "BTCUSDT",
id: 123,
orderId: 123,
side: "SELL",
price: 26832.5,
qty: 0.025,
realizedPnl: "0",
marginAsset: "USDT",
quoteQty: "670.81250",
commission: 0.00113016,
commissionAsset: "BNB",
time: 1695237604838,
positionSide: "BOTH",
buyer: false,
maker: false
}
```
Example code used:
```ts
import { USDMClient } from "binance";
const key = process.env.APIKEY || "";
const secret = process.env.APISECRET || "";
const usdmClient = new USDMClient({
api_key: key,
api_secret: secret,
beautifyResponses: true,
});
(async () => {
try {
const todayAtMidnight = new Date().setHours(0, 0, 0, 0);
const startTime = new Date(todayAtMidnight).getTime();
// @ts-ignore
const trades = await usdmClient.getAccountTrades({ startTime }); …
```
=> fix FuturesPositionTrade type

src/websocket-client.ts
Fixes #366 
Updated the parameter name `force` to `willReconnect` of method `closeAll()`, which will be consistent with parameter name for methods `closeWs()` and `close()`.
=> fix: Update websocket-client.ts

package.json, src/websocket-client.ts
`WebsocketClient`, before sending ping and pong, will make sure the WebSocket's `readyState`  is `OPEN`. This will avoid unnecesarry errors when sending ping/pong while WebSocket is not ready (such as `CONNECTING` or `CLOSING` states).
Closes #384
=> Check ws.readyState at ping

package-lock.json, package.json, src/websocket-client.ts
=> v2.10.0: fix(#402) ws diff book depth update speed for futures. Change default update speed to 100ms.

package-lock.json, package.json, src/websocket-client.ts
=> v2.10.1: fix(#402) update ms passthru

package-lock.json, package.json, src/main-client.ts, src/types/spot.ts
=> v2.10.2: feat(#411) add spot SOR order endpoints

package.json, src/main-client.ts, src/types/simpleEarn.ts
Added some simple earn endpoints as I saw https://github.com/tiagosiebler/binance/issues/386
I am confused on how to submit params for get request, proceeded with query params but there is some inconsistency across methods. sometimes as body, sometimes as url query. According to docs for get request it must be query string 
Anyone feel free to contribute more, I've just added about half of the simple earn endpoints, those are important to me.
Tried to not include breaking changes and kept naming of existing methods, tho types were outdated, not accurate on some of them
=> v2.10.4: add some missing simple earn endpoints

package.json, src/main-client.ts, src/types/shared.ts, src/types/spot.ts, src/types/websockets.ts, src/util/beautifier-maps.ts, src/websocket-client.ts
- Add `submitNewOrderList()` because `New OCO` is [deprecated on Binance API](https://binance-docs.github.io/apidocs/spot/en/#new-oco-deprecated-trade).
- Make `sumbitNewOrder()` and `replaceOrder()` generic to have correct report type for the response.
- Add missing types of `workingTime`, `selfTradePreventionMode` and `transactTime`.
- Add missing fields `W` and `V` to the `executionReport`.
- Add the `OrderResponse` type for convenience.
- Add generic `OrderResponseTypeFor<T>` for a better developer experience. Please take a look at the example below.
- Add typing for "OCO" methods having `any`.
- Add `baseUrl` to the `WSClientConfigurableOptions`, so it can be used to subscribe to SpotUserDataStream on Testnet. Closes #414 
- Detach types: `CancelRestrictions`, `CancelReplaceMode`
- …
=> v2.11.0: feat(): improved type resolution for order submit/amend methods & add "submitNewOrderList" method and related types

examples/rest-future-bracket-order.ts, examples/rest-spot-private-trade.ts, examples/rest-usdm-order.ts, package-lock.json, package.json, src/types/spot.ts, src/usdm-client.ts, tea.yaml
=> v2.11.1: fix(#424) type for newOrderRespType. minor sample fixes.

package-lock.json, package.json, src/main-client.ts, src/types/spot.ts
From docs:
According to the [announcement](https://www.binance.com/en/support/announcement/updates-on-binance-margin-sapi-endpoints-2024-03-31-a1868c686ce7448da8c3061a82a87b0c), Binance Margin will remove the following SAPI interfaces at 4:00 on March 31, 2024 (UTC). Please switch to the corresponding alternative interfaces in time:
POST /sapi/v1/margin/transfer will be removed, please replace with POST /sapi/v1/asset/transfer universal transfer
POST /sapi/v1/margin/isolated/transfer will be removed, please replace with POST /sapi/v1/asset/transfer universal transfer
POST /sapi/v1/margin/loan will be removed, please replace with the new POST /sapi/v1/margin/borrow-repay borrowing and repayment interface
POST /sapi/v1/margin/repay will be removed, please replace with the new POST …
=> Update old margin SAPI interfaces as per docs

package-lock.json, package.json, src/types/futures.ts
- Futures method "Get Income History" supports `page` param
- Adding `page` to interface `GetIncomeHistoryParams`
- Reference https://developers.binance.com/docs/derivatives/usds-margined-futures/account/rest-api/Get-Income-History
=> Add `page` to  `GetIncomeHistoryParams`

package-lock.json, package.json, src/main-client.ts, src/types/futures.ts, src/types/spot.ts
1. Added **v2** method "Add IP Restriction for Sub-Account API key". ref https://developers.binance.com/docs/sub_account/api-management/Add-IP-Restriction-for-Sub-Account-API-key
2. Added boolean field `multiAssetsMargin` to futures account info response. ref https://developers.binance.com/docs/derivatives/usds-margined-futures/account/rest-api/Account-Information-V2
3. Fixed typo in interface name `SubAccountnableOrDisableIPRestriction`-> `SubAccountEnableOrDisableIPRestriction`> (missing E in word Enable)
=> Add v2 method "Add IP Restriction for Sub-Account API key"

docs/endpointFunctionList.md, examples/apidoc/CoinMClient/getAccountComissionRate.js, examples/apidoc/USDMClient/getAccountComissionRate.js, package.json, src/coinm-client.ts, src/usdm-client.ts, test/futures-usdm/private.test.ts
Correct typo in function name from `getAccountComissionRate` to `getAccountCommissionRate`
=> fix(typo): rename getAccountComissionRate to getAccountCommissionRate

package.json, src/types/spot.ts
`SymbolExchangeInfo` is currently missing `baseCommissionPrecision` and `quoteCommissionPrecision` props.
https://developers.binance.com/docs/binance-spot-api-docs/rest-api/public-api-endpoints#exchange-information
=> feat(types/spot): add 'baseCommissionPrecision' and 'quoteCommissionPrecision' to SymbolExchangeInfo

package-lock.json, package.json, src/usdm-client.ts
Some fields for new orders can be string or number (unofficially). The existing type was unintentionally strict (on the wrong side of this). Now it allows string or number and defaults to string.
=> fix(v2.13.18, #482): pass-through number type for submit multiple orders endpoint

package-lock.json, package.json, src/types/spot.ts
I added some new entries to EnumDepositStatus in /types/spot.d.ts as the doc says at [this link](https://developers.binance.com/docs/wallet/capital/deposite-history)
The following entries were missing : 
- WrongDeposit = 7
- WaitingUserConfirm = 8
- Rejected = 2
=> update types : EnumDepositStatus

package.json, src/types/futures.ts
Add `goodTillDate` mentioned in #505
=> feat(v2.15.4, #505): Add `goodTillDate` futures order property

package-lock.json, package.json, src/main-client.ts
Fixes how the "symbols" array parameter is built into a request for the rolling window ticker endpoint:
```
const rollingTicker = await client.getRollingWindowTicker({
symbols: ['BTCUSDT', 'ETHUSDT'],
windowSize: '5m',
type: 'MINI',
});
console.log('getRollingWindowTicker', rollingTicker);
```
Fixes #507.
=> fix(v2.15.6, #507): correct handling for symbols array in rolling window tickers endpoint

package-lock.json, package.json, src/main-client.ts
Fixes missing parameters when "symbols" property is used with rolling tickers. Fixes issue discussed in #507.
=> fix(v2.5.7, #507): fix missing parameters when passing symbols in rolling tickers

package-lock.json, package.json, src/main-client.ts
Symbols were not taken into account in `MainClient::getIsolatedMarginAccountInfo` because of the extra curly braces
No breaking changes. Symbols will now be taken into account
=> fix(v2.15.10): params in getIsolatedMarginAccountInfo
